### ISSUE TITLE
Exportation d'images

### ISSUE THREAD

**Issue by MyriamPCode** [MyriamPCode/IFT-3100#13]
En cours d’exécution, il est possible d’exporter de manière interactive des
séquences de fichiers images qui correspondent au rendu d’une scène pendant
un intervalle de temps.

- [x]  Ajouter documentation dans le document de design.

**Comment by NhutTri** [comment]
Donc, on peut cliquer sur la touche "r" pour commencer l'enregistrement et on reclick pour l'arrêter. On remarque au terminal l'état de l'enregistrement est en cours ou arrêter. Par défaut, on capture 60 images par 60 fps. On reboucle et on écrase les images si on roule plus longtemps.
