### ISSUE TITLE
Primitives vectorielles

### ISSUE THREAD

**Issue by MyriamPCode** [MyriamPCode/IFT-3100#19]
Il est possible de créer de manière interactive des instances d’au moins 5 types des primitives vectorielles parmi cet ensemble : point, ligne, carré, rectangle, triangle, quadrilatère, polygone régulier, polygone irrégulier, cercle, ellipse et arc.

- [x] Ajouter la documentation dans le document design

**Comment by NhutTri** [comment]
Implémentation des objets par défaut primitives suivant : triangle, cercle, rectangle, ligne, ellipse et bezier. La forme sera générer à l'endroit qu'on click avec la souris.
